Add data converting to excel library
spaceone-dev/console-api pull request #217
Opened 2021-03-23 06:22 UTC by yuda110

### 작업 개요
excel data parser 추가

### 작업 분류
- [ ] 버그 수정
- [x] 신규 기능
- [ ] 프로젝트 구조 변경

### 작업 상세 내용
- 코드 리팩토링
- data type에 따른 data converting
    - datetime: timezone에 맞춰 readable하게 변환 (ex. 2021-03-23 02:00:02)
    - list: \n로 join (ex. ['a', 'b', 'c'] -> 'a\nb\nc')

### 생각해볼 문제
뭐 더 할 게 있을 거 같은데...뭔가 찜찜한 이 기분은 뭘까요🙃

2021-03-23 06:43 UTC, WANZARGEN requested changes

2021-03-23 06:43 UTC, WANZARGEN commented on src/lib/excel.js
> +            let cellData = data[column.key];
get value by path 를 여기서 실행해 주세요!

2021-03-24 07:13 UTC, yuda110 commented on src/lib/excel.js
> +            let cellData = data[column.key];
바꿨어열!!!

2021-03-24 08:04 UTC, WANZARGEN approved these changes

2021-03-24 08:04 UTC, WANZARGEN commented on src/lib/excel.js
> +                    });
이 부분은

```typescript
convertedData = cellData.map((d) => {
    const selectedData = find(referenceResource, { key: d });
    if (selectedData) return selectedData.name;
    return d;
});
```

이렇게 바꾸면 좀 더 명확할 것 같아요!

2021-03-24 08:04 UTC, WANZARGEN commented on src/lib/excel.js
> +                if (enumItems) cellData = enumItems[cellData];
이 부분은 방어코드로

```typescript
if (enumItems?[cellData] !== undefined) cellData = enumItems[cellData];
```

이렇게 `enumItems[cellData]`가 없는 경우도 대응하면 좋을 것 같아요!

2021-03-24 08:05 UTC, WANZARGEN commented
고생 많으셨습니다 !!

2021-03-24 08:07 UTC, yuda110 commented on src/lib/excel.js
> +            const reference = field.reference;
헐 이렇게 할 수 있군요

2021-03-24 08:22 UTC, yuda110 commented
모두 수정했습니다!

2021-03-24 08:22 UTC, merged