feat: implement cost analyze api
spaceone-dev/console-api pull request #355
Opened 2021-11-03 12:37 UTC by whdalsrnt

### 작업 분류
- [x] 신규 기능
- [ ] 버그 수정
- [ ] 기능 개선
- [ ] 리팩토링 및 구조 변경
- [ ] 기타 (문서, CI/CD 워크플로 변경 등)

### 작업 내용
Cost Analyze API 추가

2021-11-03 12:42 UTC, WANZARGEN commented on src/controllers/cost-analysis/cost/analyze-costs.ts
> +    if (Object.keys(GRANULARITY_FORMAT).indexOf(params.granularity) < 0) {
```suggestion
    if (!Object.keys(GRANULARITY_FORMAT).includes(params.granularity)) {
```

이렇게 하면 가독성이 더 좋아질 것 같습니다!

2021-11-03 12:44 UTC, WANZARGEN commented on src/controllers/cost-analysis/cost/analyze-costs.ts
> +    });
```suggestion
    if (params.filter) {
        requestParams.query.filter = cloneDeep(params.filter);
        
        requestParams.query.filter.push({
            key: 'billed_at',
            value: params.start,
            operator: 'datetime_gte'
        });
    
        requestParams.query.filter.push({
            key: 'billed_at',
            value: params.end,
            operator: 'datetime_lt'
        });
    }
```

엇 아래 두 구문이 if 블럭 안에 들어가야 할 것 같아요!

2021-11-03 12:46 UTC, WANZARGEN commented on src/controllers/cost-analysis/cost/analyze-costs.ts
> +    }
params 에 `domain_id` 들어가는 이유는 위젯에 쓰이는 api 라서 그런 것 맞나요? ㅎㅎ

2021-11-03 12:48 UTC, WANZARGEN requested changes
엄청난 통계 쿼리들의 향연... 고생 많으셨습니다!!!!!!!!
문제될만한 부분이 있어서 코멘트 달았습니다!

2021-11-03 12:51 UTC, WANZARGEN approved these changes

2021-11-04 02:41 UTC, merged

2021-11-08 14:27 UTC, whdalsrnt commented on src/controllers/cost-analysis/cost/analyze-costs.ts
> +    if (Object.keys(GRANULARITY_FORMAT).indexOf(params.granularity) < 0) {
옙 다음 패치에 처리 완료했습니다.

2021-11-08 14:28 UTC, whdalsrnt commented on src/controllers/cost-analysis/cost/analyze-costs.ts
> +    }
옙 혹시나 해서 넣어 놨어요!